// pokemon
const GET_POKEMON_REQUEST = "GET_POKEMON_REQUEST";
const GET_POKEMON_SUCCESS = "GET_POKEMON_SUCCESS";
const GET_POKEMON_ERROR = "GET_POKEMON_REQUEST";

export { GET_POKEMON_REQUEST, GET_POKEMON_SUCCESS, GET_POKEMON_ERROR };
